#!/usr/bin/env python

import smtplib
import sys

from email.mime.text import MIMEText

filename = sys.argv[1]

filepath="/root/reports/{}".format(filename)

fp = open(filepath, 'rb')
#fp = open("/root/reports/2020-04-23", 'rb')
# Create a text/plain message
msg = MIMEText(fp.read())
fp.close()

#textfile="2020-04-23"

sender = 'custcare@xyz.com'
recipients = ['abc@xyz.com','customer@domain.com']

msg['Subject'] = 'VPN Report for %s' %filename
msg['From'] = sender
msg['To'] = ", ".join(recipients)

smtpobj=smtplib.SMTP('192.168.1.200',25)
smtpobj.sendmail(sender,recipients,msg.as_string())
smtpobj.quit()
