#!/bin/bash



yesdate=`date +"%b %e" --date=" 1 day ago"`
filename=`date +%F --date="1 day ago"`
archivefile=`date +%Y%m%d --date="1 day ago"`
#echo $yesdate


/usr/bin/openvpn-user list | grep -v test | grep -v '^$' > /root/bin/users
\


for i in `cat /root/bin/users`; do echo "-------- Report for user $i ---------------" ; zgrep -h "$yesdate" /var/log/endian/jobsengine /var/log/archives/endian/jobsengine-$archivefile.gz |grep OPENVPNJOB-openvpn  | grep $i | awk {'print $1,$2,$3,$8,$10,$12,$16,$17,$18,$19,$20'}  ; done > /root/reports/$filename

/usr/bin/python /root/bin/mail-report $filename
